version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ../mbti_with_music_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: db
    image: dockermkkang/mbti_db:0.4
    ports:
      - "3307:3306"
    environment:
      - MARIADB_USER=mbti_music
      - MARIADB_PASSWORD=mbti_music
      - MARIADB_ROOT_PASSWORD=mariadb
