version: "3.9"
services:
  front:
    container_name: front
    build:
      context: .
    ports:
      - "3000:80"
    environment:
      - NGINX_HOST=back
      - NGINX_PORT=4000
    depends_on:
      - back
  back:
    container_name: back
    build:
      context: ../mbti_with_music_backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
    depends_on:
      - db
  db:
    container_name: db
    build:
      context: ../mbti_with_music_db
    environment:
      - MARIADB_USER=mbti_music
      - MARIADB_PASSWORD=mbti_music
      - MARIADB_DATABASE=mbti_music
      - MARIADB_ROOT_PASSWORD=mariadb
    ports:
      - "3307:3306"
