version: "3.9"
services:
  front:
    container_name: front
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - back
  back:
    container_name: back
    build:
      context: ../mbti_with_music_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: db
    build:
      context: ../mbti_with_music_db
    ports:
      - "3307:3306"
